before_script:
  - git clone https://github.com/meizikeai/gitlab-shell-practice.git

# after_script:
  # - rm -rf gitlab-shell-practice

.access_branch_template: &access_branch
  only:
    - master
    - test

variables:
  deploys: /home/work/koa-typescript-practice
  project: koa-typescript-practice
  scripts: gitlab-shell-practice
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=XXX
  feishu: https://open.feishu.cn/open-apis/bot/hook/XXX

stages:
  - install
  - build
  - deploy-development
  - deploy-production

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - build/
    - node_modules/
    - version

install:
  <<: *access_branch
  stage: install
  script:
    - bash $scripts/declare.sh
    - bash $scripts/install.sh

build:
  <<: *access_branch
  stage: build
  script:
    - bash $scripts/build.sh

deploy-development:
  stage: deploy-development
  when: on_success
  script: 
    - bash $scripts/rollback.sh
    - bash $scripts/deploy.sh "work@192.168.0.1"
  environment:
    name: development
  only:
    - test

deploy-production:
  stage: deploy-production
  when: manual
  script: 
    - bash $scripts/rollback.sh
    - bash $scripts/deploy.sh "work@192.168.1.1 work@192.168.1.2"
  environment:
    name: production
  only:
    - master
